added: Docker
mi-classroom/mi-web-technologien-beiboot-ss2024-Liobabrandhoff pull request #3
Opened 2024-07-15 11:51 UTC by Liobabrandhoff

Mit dieser Änderung ist es nun möglich bei der lokalen Ausführung Docker zu verwenden.

2024-07-15 15:10 UTC, jona-d01 commented
Die generierten Bilder sollten nicht mit im Projekt gespeichert bzw. committet werden und mithilfe der `.gitignore` Datei ausgeschlossen werden!

2024-07-15 18:29 UTC, jona-d01 requested changes
Hier ein paar Änderungsvorschläge, die vor dem Mergen betrachtet werden sollten.

2024-07-15 18:29 UTC, jona-d01 commented on .dockerignore
> +.dockerignore
Die `Dockerfile` und die `.dockerignore`-Datei sollten nicht innerhalb der `.dockerignore` aufgelistet sein!\
Die `.dockerignore`-Datei dient dazu, Dateien und Verzeichnisse aus dem Build-Kontext auszuschließen. Wenn die `Dockerfile` oder die `.dockerignore` selbst in der `.dockerignore` aufgelistet werden, wird Docker sie beim Erstellen des Images ignorieren. Die `.dockerignore` sollte nur die Dateien und Verzeichnisse enthalten, die nicht im Image enthalten sein sollen, wie z. B. temporäre Dateien, Build-Artefakte oder ungenutzte Ressourcen.
```suggestion

```

2024-07-15 18:29 UTC, jona-d01 commented on README.md
> +docker run -p 8000:8000 --name beiboot-projekt -d docker run -d beiboot-projekt
Hier gibts einen kleinen Tippfehler.
Das `docker run -d` am Ende ist doppelt.

```suggestion
docker run -p 8000:8000 --name beiboot-projekt -d beiboot-projekt
```

2024-07-17 10:17 UTC, Liobabrandhoff commented
Alle Anmerkungen korrigiert

2024-07-17 10:27 UTC, jona-d01 commented
Die Frames / Bilder am besten noch aus dem Branch löschen, damit diese nicht versehentlich noch mit gemergt werden 😉

2024-09-16 08:36 UTC, merged